# Config de conexión
sonar.projectKey=TBD-LAB3
sonar.projectName=TBD-LAB3
sonar.host.url=http://localhost:9000
sonar.token=sonar.token=${SONAR_TOKEN}

# Config de proyecto
sonar.sources=LAB-TBD/src/main/java
sonar.scm.exclusions.disabled=true