name: OWASP Depedency Check Frontend 22

on:
  workflow_call:

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
      - name: Install dependencies
        working-directory: Frontend
        run: |
          npm install  
      - name: Ejecutar OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: FullScanFront
        with:
          project: 'my-project'
          path: '.'
          format: 'HTML'
          out: './dependency-check-report'
        
      - name: Subir el reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report-front
          path: ./dependency-check-report
  call-sonarcloud:
    needs: owasp-dependency-check
    uses: ./.github/workflows/sonar_cloud.yml
    secrets: inherit
