name: OWASP Dependency-Check Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cache de dependencias de Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('LAB-TBD/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # 4. Ejecutar OWASP Dependency-Check
      - name: Run OWASP Dependency-Check
        working-directory: LAB-TBD  
        run: mvn org.owasp:dependency-check-maven:check

      # 5. Subir informe como artefacto
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report-back
          path: LAB-TBD/target/dependency-check-report.html
  call-dependencycheckfront:
    needs: dependency-check
    uses: ./.github/workflows/checkfrontdependency.yml
    secrets: inherit
