name: Snyk Security Scan

on:
  push:
    branches:
      - DevSecOps---David
  pull_request:
    branches:
      - DevSecOps---David

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Usa la versión de Node.js que necesita tu proyecto

      # Paso 3: Instalar dependencias del proyecto
      - name: Install dependencies
        working-directory: Frontend
        run: npm install

      # Paso 4: Autenticación con Snyk
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Paso 5: Escanear vulnerabilidades usando Snyk
      - name: Run Snyk test
        run: snyk test

      # Paso 6: (Opcional) Subir el informe de Snyk como un artefacto
      - name: Upload Snyk Report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk-report.json