name: Dependency Check

on:
  push:
    branches:
      - DevSecOps---David
  pull_request:
    branches:
      - DevSecOps---David
jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   
 # Adjust to your preferred Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run OWASP Dependency Check
        uses: jeremylong/DependencyCheck-Action@v1
        with:
          fail-build-on-vulnerabilities: true
          format: ALL
          scan: package-lock.json
          suppression-file: dependency-check-suppression.xml # Optional suppression file